### PR TITLE
comments.md

### PR DESCRIPTION
**Pull request by sebi-avg-yt-number-1**

### CODE REVIEW

**Review by CertifiedRice — COMMENTED** [review]
Dude, what is `== This is a comment`. `==` is not a valid comment

**Comment by CertifiedRice** [comment]
@glaukiol1 
is `==` a valid comment?

**Comment by glaukiol1** [comment]
no, `==` is not a valid comment.

**Comment by glaukiol1** [comment]
idk what he/she is talking about

**Comment by glaukiol1** [comment]
Just to clarify, `==` is a matching operator, it is used to check if things equal, like below;
```rusted
if 1 == 1 then 123 else 321
```
The above checks if `1 is equal to 1`, so no, you can look at `docs/comments.md` for comment types.

**Pull request merged**
